/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ID.java
 *
 * Created on 26 mai 2010, 11:18:39
 */
package App2012;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author choukri
 */
public class Auth extends javax.swing.JFrame {
    private static final long serialVersionUID = 1L;

    /** Creates new form ID */
    private App m = new App();

    public Auth() {

        initComponents();
//        this.setLocationRelativeTo(null);
  //      this.setIconImage(new ImageIcon(getClass().getResource("/MAC/logo.png")).getImage());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Authentification = new javax.swing.JPanel();
        txtlog = new javax.swing.JTextField();
        txtpwd = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        um5a = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fsr = new javax.swing.JLabel();
        FSA = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Application de chiffrement GSM  MMS 2010/12");
        setLocation(new java.awt.Point(250, 150));
        setPreferredSize(new java.awt.Dimension(751, 434));

        Authentification.setBackground(new java.awt.Color(255, 255, 255));
        Authentification.setPreferredSize(new java.awt.Dimension(751, 434));

        txtlog.setForeground(new java.awt.Color(255, 0, 0));
        txtlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlogActionPerformed(evt);
            }
        });

        txtpwd.setForeground(new java.awt.Color(255, 0, 0));
        txtpwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpwdActionPerformed(evt);
            }
        });
        txtpwd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpwdKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Login");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("password");

        jToggleButton1.setText("OK");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setText("Exit");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("© Copyright  Chokri NOUAR       2010-2012");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App2012/Key.jpg"))); // NOI18N

        um5a.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App2012/um5a.gif"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setText("Faculté des Sciences ");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel6.setText("RABAT - AGDAL");

        fsr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App2012/fsr.jpg"))); // NOI18N

        FSA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App2012/fsa1.jpg"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel11.setText("AGADIR");

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel12.setText("Faculté des Sciences ");

        javax.swing.GroupLayout AuthentificationLayout = new javax.swing.GroupLayout(Authentification);
        Authentification.setLayout(AuthentificationLayout);
        AuthentificationLayout.setHorizontalGroup(
            AuthentificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AuthentificationLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(200, 200, 200))
            .addGroup(AuthentificationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AuthentificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AuthentificationLayout.createSequentialGroup()
                        .addGroup(AuthentificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(AuthentificationLayout.createSequentialGroup()
                                .addComponent(um5a)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                .addGroup(AuthentificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FSA)
                                .addGap(50, 50, 50)
                                .addGroup(AuthentificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(AuthentificationLayout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(AuthentificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(AuthentificationLayout.createSequentialGroup()
                                        .addComponent(txtlog, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 267, Short.MAX_VALUE)
                                        .addComponent(jLabel2))
                                    .addGroup(AuthentificationLayout.createSequentialGroup()
                                        .addComponent(jToggleButton1)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(AuthentificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jToggleButton2)
                                    .addComponent(txtpwd, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fsr))
                    .addGroup(AuthentificationLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        AuthentificationLayout.setVerticalGroup(
            AuthentificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AuthentificationLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(AuthentificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(um5a)
                    .addGroup(AuthentificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(AuthentificationLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel6)
                            .addGap(12, 12, 12))
                        .addComponent(fsr))
                    .addComponent(FSA, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addGroup(AuthentificationLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AuthentificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtlog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtpwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AuthentificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Authentification, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Authentification, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlogActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtlogActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
//String Login;
//String pwd;
        String Login = txtlog.getText();
        @SuppressWarnings("deprecation")
        String pwd = txtpwd.getText();




        //JOptionPane   jop3 = new JOptionPane();
        if ((Login.compareToIgnoreCase("chokri") == 0) && (pwd.compareToIgnoreCase("admin") == 0)) //{
        //   if(pwd.compareTo("admin")==0)
        {
            getM().setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "Password invalide", "Erreur", JOptionPane.ERROR_MESSAGE);
        }


//}else
        // JOptionPane.showMessageDialog(null, "Login invalide", "Erreur", JOptionPane.ERROR_MESSAGE);

        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
//this.dispose();
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void txtpwdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpwdKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            String Login = txtlog.getText();
            @SuppressWarnings("deprecation")
            String pwd = txtpwd.getText();

            //JOptionPane   jop3 = new JOptionPane();
            if ((Login.compareToIgnoreCase("chokri") == 0) && (pwd.compareToIgnoreCase("admin") == 0)) //{
            //   if(pwd.compareTo("admin")==0)
            {
                getM().setVisible(true);
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(null, "Password invalide", "Erreur", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_txtpwdKeyPressed

    private void txtpwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpwdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new Auth().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Authentification;
    private javax.swing.JLabel FSA;
    private javax.swing.JLabel fsr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JTextField txtlog;
    private javax.swing.JPasswordField txtpwd;
    private javax.swing.JLabel um5a;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the m
     */
    public App getM() {
        return m;
    }

    /**
     * @param m the m to set
     */
    public void setM(App m) {
        this.m = m;
    }
}
