/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package App2012;

/**
 *
 * @author choukri
 */
public class test extends javax.swing.JFrame {
    
    
    public String StringToBinary(String text) {
        String textBinary = "";
        String s7 = "0000000", s6 = "000000", s5 = "00000", s4 = "0000", s3 = "000", s2 = "00", s1 = "0";


        int textLenth = text.length();
        //on decoupe le texte sous forme de carctères
        char[] c = text.toCharArray();
        //
        int[] b = new int[textLenth];
        String[] st = new String[textLenth];
        //
        for (int g = 0; g < textLenth; g++) {
            b[g] = (byte) c[g];//on converti chaque carctère a son code ascii
            st[g] = Integer.toBinaryString(b[g]);//on converti chaque code ascci sous sa forme binaire
            // System.out.println(st[g]);
            if (st[g].length() == 1) {
                st[g] = s7 + st[g];
            }//pour avoir des squences de 8 bits
            if (st[g].length() == 2) {
                st[g] = s6 + st[g];
            }//ca sera utile por le découpage pendant
            if (st[g].length() == 3) {
                st[g] = s5 + st[g];
            }//le déchifrement
            if (st[g].length() == 4) {
                st[g] = s4 + st[g];
            }
            if (st[g].length() == 5) {
                st[g] = s3 + st[g];
            }
            if (st[g].length() == 6) {
                st[g] = s2 + st[g];
            }
            if (st[g].length() == 7) {
                st[g] = s1 + st[g];
            }
            textBinary += st[g];
            //System.out.println(g+"\t"+st[g].toString());


        }
        //System.out.println(textBinary);
        return textBinary;
    }
    
    
    public String généré(String kg,String ps,String qs,int initial){
        
        StringBuilder k = new StringBuilder(StringToBinary(kg));
        int tai = k.length();
        char [] ks = new char [tai];
        int p = Integer.parseInt(ps);
        int q = Integer.parseInt(qs);
                int i=initial*24;
                for (int j=1; j<114;j++)
                    {
                        i =(p*i+q)%192;
                        ks[j] = k.charAt(i);
                        }
        return new String(ks);        
    }
    
    
    public String généré1(String kg,int p,int q,int initial){
        
        StringBuilder cl = new StringBuilder (StringToBinary(kg));
        String ks="";
                int i=initial*24;
                for (int j=0; j<14;j++)
                    {
                        i =(p*i+q)%192;
                        ks+=cl.charAt(i);
                        }
        return ks;        
    }
    
    

    /**
     * Creates new form test
     */
    public test() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(48, 48, 48)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jButton1)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(txt1)
                        .add(txt2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(29, 29, 29)
                .add(txt1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(28, 28, 28)
                .add(txt2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 90, Short.MAX_VALUE)
                .add(jButton1)
                .add(68, 68, 68))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String KG = txt1.getText();   
        String ps = "12";
        String qs = "23";    
        int a = 7;
        String af = généré(KG,ps,qs,a);
        
        
        
        txt2.setText(af);
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new test().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    // End of variables declaration//GEN-END:variables
}
